[package]
name = "bat-markets-bybit"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Bybit linear USDT futures adapter for bat-markets"
documentation = "https://docs.rs/bat-markets-bybit"
readme = "../../README.md"
keywords = ["exchange", "futures", "bybit", "trading"]
categories = ["api-bindings", "finance", "asynchronous"]

[dependencies]
bat-markets-core = { path = "../bat-markets-core", version = "0.2.0" }
parking_lot.workspace = true
rust_decimal.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[lints]
workspace = true
